class BlockMember {
      void forLoop() {
    for (String a : listA) {
    }
        for (String a : listA) {
    }



        for (String a : listA) {
    }

    for (String a : listA) {
    }

  }

  void normalFor(){
      for (integer i = 0; i < 10; i++) {
    }
      for (integer i = 0; i < 10; i++) {
      System.debug('h');
    }

      for (integer i = 0; i < 10; i++) {
      System.debug('h');
    }


      for (integer i = 0; i < 10; i++) {
      System.debug('h');
    }

  }


}
