class A {
  {
    new List<Id>{ '0010B00001kL7i0QAC' };

    String[] values = new String[0];

    stringArray = new String[0];
    stringArray = new String[0];

    Integer index = 5;
    stringArray = new List<String>(index);
    stringArray = new List<String>(index);

    List<List<String>> listOfList = new List<List<String>>();

    List<List<String>> listOfList = new List<List<String>>(0);
  }
}
