class HelloWorld {
  {
    Boolean aaaaaaaaaaaaaaaaaa =
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb > 1 && ccccccccccccccccccccc > 1;

    aaaaaaaaaaaaaaaaaa =
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb > 1 && ccccccccccccccccccccc > 1;

    aaaaaaaaaaaaaaaaaa =
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb > 1
      && cccccccccccccccccccccccccccccccccc > 1;

    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb > 1
    && ccccccccccccccccccccccccccccc > 1;
  }
}
