public class TestSObjectDisableBehaviourConstructor
  implements fflib_SObjectDomain.IConstructable {
}
public virtual inherited sharing class TriggerActionFlow
  implements TriggerAction.BeforeInsert, TriggerAction.AfterInsert, TriggerAction.BeforeUpdate, TriggerAction.AfterUpdate, TriggerAction.BeforeDelete, TriggerAction.AfterDelete, TriggerAction.AfterUndelete {
}
public virtual class fflib_ClassicUnitOfWorkFactory
  extends fflib_Application.UnitOfWorkFactoryimplements fflib_IUnitOfWorkFactory {
}
