class ExtendImplementClass
  extends FirstExtendimplements FirstImplement, SecondImplement {
  public virtual class VirtualExtendInnerClass extends FirstExtend {
  }

  private abstract class AbstractImplementInnerClass implements FirstImplement {
  }

  global class ExtendImplementInnerClass
    extends FirstExtendimplements FirstImplement, SecondImplement {
  }

  public override Integer compareTo(Object anotherObject) {
  }
}
