class A {
  {
    Boolean aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa =
      [
        SELECT
          Id,
          Name______bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_c,
          Kname_________________b_______________aa_c
        FROM Contact
      ]
      > 0;

    [
      SELECT
        Id,
        Name______bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_c,
        Kname_________________b_______________aa_c
      FROM Contact
    ]
      .b()
      .c();

    [
      SELECT
        Id,
        Name______bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_c,
        Kname_________________b_______________aa_c
      FROM Contact
    ]
      .b()
      .c();
  }
}
