name: Publish to crates.io

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags (e.g., v1.0.0)

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to crates.io
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Publish to crates.io
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          # Ensure Cargo.lock is up-to-date
          cargo check
          # Publish to crates.io
          cargo publish --no-verify

